version: 2 
jobs: 
  build: 
    working_directory: ~/circleci-demo-java-spring
    
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    
    steps:
      - checkout
      - run: mvn dependency:go-offline 
      - run: mvn package # 実際のテストを実行します

      - store_test_results: 
          path: target/surefire-reports

      - store_artifacts: 
          path: target/demo-cctest-0.0.1-SNAPSHOT.jar